version: "3.5"
services:
  neuralsentinel_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    volumes:
      - ./backend/datasets:/usr/src/app/datasets
      - ./backend/models:/usr/src/app/models
    restart: always

  neuralsentinel_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
