import axios from "axios";
import { useImageStore } from "./store/imagestore";



/**
 * Class to define an axios request
 * @property {string | null} baseurl: the protocol, hostname, and port number of the machine sending the request. ex: http://example.com
 */
class AxiosRequest {
  #baseurl = ""
  #url = ""
  #method = "get"
  
  constructor(burl=null ) {
    if (burl) {
      this.#baseurl = burl
    } else {
      this.#baseurl = window.location.origin
    }
  }

  get basicRequest() {
    return {
      "url": this.#url,
      "method": this.#method, // default
      "baseURL": this.#baseurl
    }
  }

  /**
   * @param {'get' | 'put'} value: The two possible methods. Must be set before sending the request
   */
  set method(value) {
    this.#method = value
  }

  /**
   * @param {string} value: the endpoint. ex: /endpoint. Must be set before sending the request
   */
  set url(value) {
    this.#url = value
  }
}

class API {

  #axios
  constructor() {
    this.#axios = axios.create()
  }

  async #executecall(method, url, addConfig=null) {
    const requestconfig = new AxiosRequest(window.location.origin)
    requestconfig.method = method
    requestconfig.url = url
    let request = requestconfig.basicRequest
    if (addConfig && Object.keys(addConfig).length > 0) {
      for (let item of Object.keys(addConfig)) {
        request[item] = addConfig[item]
      }
    }
    let result = await this.#axios.request(request)
    return result
  }

  async initializescenario(env, model) {
    const conf = {
      params: {
        environment: env,
        scenario: model
      }
    }
    try {
      const rs = await this.#executecall("post", "api/initialize", conf)
      if (rs.status == 200) {
        return 0
      } else {
        return 1
      }
    } catch (error) {
      console.error(error)
      return 1
    }
    
  }

  async fgsm(samples) {
    const store = useImageStore()
    store.resetstore()
    const conf = {
      params: {
        n_sample: samples
      }
    }
    try {
    const rs = await this.#executecall("get", "api/fgsm", conf)
      if (rs.status == 200) {
        this.#loadadversarialimages(rs.data["data"], samples)
        this.#loadImpactImages(rs.data["impact"], samples)
        return rs.data["metrics"]
      } else {
        return rs.statusText
      }
    } catch (error) {
      return error
    }
  }

  async bim(samples, steps) {
    const store = useImageStore()
    store.resetstore()
    const conf = {
      params: {
        n_sample: samples,
        steps: steps
      }
    }
    try {
      const rs = await this.#executecall("get", "api/bim", conf)
      if (rs.status == 200) {
        this.#loadadversarialimages(rs.data["data"], samples)
        this.#loadImpactImages(rs.data["impact"], samples)
        return rs.data["metrics"]
      } else {
        return rs.statusText
      }
    } catch (error) {
      return error
    }
  }

  async pgd(samples, steps) {
    const store = useImageStore()
    store.resetstore()
    const conf = {
      params: {
        n_sample: samples,
        steps: steps
      }
    }
    try {
    const rs = await this.#executecall("get", "api/pgd", conf)
      if (rs.status == 200) {
        this.#loadadversarialimages(rs.data["data"], samples)
        this.#loadImpactImages(rs.data["impact"], samples)
        return rs.data["metrics"]
      } else {
        return rs.statusText
      }
    } catch (error) {
      return error
    }
  }

  async trojan(samples, steps) {
    const store = useImageStore()
    store.resetstore()
    const conf = {
      params: {
        n_sample: samples,
        steps: steps
      }
    }
    try {
    const rs = await this.#executecall("get", "api/trojaning", conf)
      if (rs.status == 200) {
        this.#loadadversarialimages(rs.data["data"], samples)
        this.#loadImpactImages(rs.data["impact"], samples)
        return {status:rs.status, data:rs.data["metrics"] }
      } else {
        return {status:rs.status, data:rs.statusText}
      }
    } catch (error) {
      return {status:error.status, data:error.message}
    }
  }

  /**
   * loads the adversarial images generated by the attack
   * @param {String} json: the data returned by the attack analysis
   * @param {Number} samples: number of samples requested 
   */
  async #loadadversarialimages(json, samples) {
    const store = useImageStore()
    store.switchadversarialloadstatus()
    for (let i = 0; i < samples; i++) {
      let conf = {
        data: json[`input_${i}`],
      }
      const rs = await this.#executecall("post", "api/visualization", conf)
      if (rs.status == 200) {
        store.addadversarialsamples(rs.data)
      } else {
        store.switchadversarialloadstatus()
        return rs.statusText
      }
    }
    store.switchadversarialloadstatus()
    return 'Success'
  }

  async #loadImpactImages(json, samples) {
    const store = useImageStore()
    store.switchimpactloadstatus()
    for (let i = 0; i < samples; i++) {
      const conf = {
        data: json[`input_${i}`],
        responseType: 'blob'
      }
      const rs = await this.#executecall("post", "api/interpretability", conf)
      if (rs.status == 200) {
          store.addImpactBlob(rs.data)
      } else {
        store.switchimpactloadstatus()
        return rs.statusText
      }
    }
    store.switchimpactloadstatus()
    return 'Success'
  }
}

const api = new API()
export default api
